[en]
aliases = [ "en-GB", "en-US",]
recognition = "English"

[zh]
aliases = [ "zh-Hans", "zh-Hant",]
recognition = "中文"

[zh-Hans]
aliases = [ "zh-CN", "zh-SG",]
description = "simplified Chinese"
recognition = "简体中文"

[zh-Hans-CN]
description = "PRC Mainland Chinese in simplified script"

[zh-Hans-HK]
description = "Hong Kong Chinese in simplified script"

[zh-Hans-MO]
description = "Macao Chinese in simplified script"

[zh-Hans-SG]
description = "Singapore Chinese in simplified script"

[zh-Hans-TW]
description = "Taiwan Chinese in simplified script"

[zh-Hant]
aliases = [ "zh-HK", "zh-MO", "zh-TW",]
description = "traditional Chinese"
recognition = "繁體中文"

[zh-Hant-CN]
description = "PRC Mainland Chinese in traditional script"

[zh-Hant-HK]
description = "Hong Kong Chinese in traditional script"

[zh-Hant-MO]
description = "Macao Chinese in traditional script"

[zh-Hant-SG]
description = "Singapore Chinese in traditional script"

[zh-Hant-TW]
description = "Taiwan Chinese in traditional script"
